from __future__ import annotations

from copy import deepcopy


def initial_state() -> dict:
    return deepcopy(
        {
            "channels": [
                {
                    "id": "email",
                    "label": "Email",
                    "status": "healthy",
                    "queueDepth": 38,
                    "activeSessions": 12,
                    "avgWaitMinutes": 18,
                    "targetMinutes": 30,
                    "slaRisk": 5,
                    "health": 94,
                    "intakeEnabled": True,
                },
                {
                    "id": "chat",
                    "label": "Web chat",
                    "status": "degraded",
                    "queueDepth": 21,
                    "activeSessions": 16,
                    "avgWaitMinutes": 7,
                    "targetMinutes": 3,
                    "slaRisk": 9,
                    "health": 72,
                    "intakeEnabled": True,
                },
                {
                    "id": "phone",
                    "label": "Phone and voice",
                    "status": "healthy",
                    "queueDepth": 11,
                    "activeSessions": 8,
                    "avgWaitMinutes": 4,
                    "targetMinutes": 5,
                    "slaRisk": 2,
                    "health": 88,
                    "intakeEnabled": True,
                },
                {
                    "id": "whatsapp",
                    "label": "WhatsApp",
                    "status": "healthy",
                    "queueDepth": 32,
                    "activeSessions": 20,
                    "avgWaitMinutes": 10,
                    "targetMinutes": 15,
                    "slaRisk": 4,
                    "health": 91,
                    "intakeEnabled": True,
                },
                {
                    "id": "internal",
                    "label": "Internal handoffs",
                    "status": "paused",
                    "queueDepth": 12,
                    "activeSessions": 2,
                    "avgWaitMinutes": 34,
                    "targetMinutes": 45,
                    "slaRisk": 4,
                    "health": 74,
                    "intakeEnabled": False,
                },
            ],
            "customers": [
                {
                    "id": "cust-1",
                    "name": "Maya Roberts",
                    "company": "Northstar Retail",
                    "title": "Operations Manager",
                    "email": "maya.roberts@example.com",
                    "phone": "+1 415 555 0187",
                    "location": "San Francisco, CA",
                    "healthScore": 38,
                    "csat": 3.7,
                    "openValue": "$18.4k",
                },
                {
                    "id": "cust-2",
                    "name": "Leo Ahmed",
                    "company": "BrightCart",
                    "title": "Store Owner",
                    "email": "leo.ahmed@example.com",
                    "phone": "+44 20 5555 0150",
                    "location": "London, UK",
                    "healthScore": 61,
                    "csat": 4.1,
                    "openValue": "$6.1k",
                },
                {
                    "id": "cust-3",
                    "name": "Aisha Bello",
                    "company": "Nimbus Energy",
                    "title": "Support Director",
                    "email": "aisha.bello@example.com",
                    "phone": "+234 803 555 0140",
                    "location": "Lagos, Nigeria",
                    "healthScore": 46,
                    "csat": 3.9,
                    "openValue": "$24.2k",
                },
            ],
            "agents": [
                {
                    "id": "agent-1",
                    "name": "Amara Lee",
                    "role": "Omni Agent",
                    "availability": "available",
                    "skills": ["Email", "Portal", "Billing"],
                    "load": 11,
                    "capacity": 16,
                    "occupancy": 69,
                    "csat": 94,
                },
                {
                    "id": "agent-2",
                    "name": "Noah Chen",
                    "role": "Live Channels Lead",
                    "availability": "busy",
                    "skills": ["Chat", "WhatsApp", "SMS"],
                    "load": 18,
                    "capacity": 20,
                    "occupancy": 90,
                    "csat": 91,
                },
                {
                    "id": "agent-5",
                    "name": "Zara Okafor",
                    "role": "Partner Support",
                    "availability": "available",
                    "skills": ["Partner systems", "Internal", "Engineering handoff"],
                    "load": 6,
                    "capacity": 12,
                    "occupancy": 50,
                    "csat": 95,
                },
            ],
            "tickets": [
                {
                    "id": "conv-1001",
                    "ticketNumber": "OMNI-1001",
                    "customerId": "cust-1",
                    "channelId": "email",
                    "subject": "Refund still missing after promised callback",
                    "preview": "Customer says the refund has not posted and the promised callback never happened.",
                    "status": "open",
                    "priority": "urgent",
                    "sentiment": "at-risk",
                    "intent": "Refund dispute",
                    "group": "Billing Operations",
                    "assigneeId": "agent-1",
                    "createdAt": "2026-05-27T07:15:00+01:00",
                    "updatedAt": "2026-05-27T07:55:00+01:00",
                    "firstResponseDue": "2026-05-27T08:00:00+01:00",
                    "resolutionDue": "2026-05-27T12:00:00+01:00",
                    "slaState": "risk",
                    "language": "English",
                    "unread": True,
                    "tags": ["billing", "callback-missed", "vip"],
                    "tasks": [
                        {"id": "task-1001-1", "label": "Confirm payment processor trace", "done": False},
                        {"id": "task-1001-2", "label": "Call customer before 08:30", "done": False},
                    ],
                    "timeline": [
                        {
                            "id": "event-1001-1",
                            "type": "customer-message",
                            "channelId": "email",
                            "author": "Maya Roberts",
                            "authorRole": "customer",
                            "timestamp": "2026-05-27T07:15:00+01:00",
                            "body": "The refund still has not posted and nobody called me back yesterday.",
                        }
                    ],
                    "copilot": {
                        "summary": "Customer has repeat promise misses and likely needs a confirmed payment trace plus callback owner.",
                        "intent": "Refund dispute",
                        "sentiment": "at-risk",
                        "autoTags": ["billing", "refund", "promise-miss"],
                        "slaReason": "First response is near breach because the customer has already waited through a missed callback.",
                        "suggestedReply": "I am confirming the processor trace now and will call you with a confirmed status within 30 minutes.",
                        "suggestedArticle": "Refund trace verification checklist",
                        "escalation": "Escalate to Billing Operations if trace is missing after one check.",
                        "recommendedAction": "Assign a callback owner and confirm the payment trace before responding.",
                        "confidence": 92,
                    },
                },
                {
                    "id": "conv-1002",
                    "ticketNumber": "OMNI-1002",
                    "customerId": "cust-2",
                    "channelId": "whatsapp",
                    "subject": "Delivery ETA changed twice",
                    "preview": "Customer wants a firm delivery ETA after repeated changes in the WhatsApp thread.",
                    "status": "pending",
                    "priority": "high",
                    "sentiment": "frustrated",
                    "intent": "Fulfillment follow-up",
                    "group": "Fulfillment",
                    "assigneeId": "agent-2",
                    "createdAt": "2026-05-27T06:40:00+01:00",
                    "updatedAt": "2026-05-27T07:35:00+01:00",
                    "firstResponseDue": "2026-05-27T06:55:00+01:00",
                    "resolutionDue": "2026-05-27T14:00:00+01:00",
                    "slaState": "healthy",
                    "language": "English",
                    "unread": False,
                    "tags": ["delivery", "eta", "whatsapp"],
                    "tasks": [{"id": "task-1002-1", "label": "Confirm courier scan", "done": True}],
                    "timeline": [
                        {
                            "id": "event-1002-1",
                            "type": "social-dm",
                            "channelId": "whatsapp",
                            "author": "Leo Ahmed",
                            "authorRole": "customer",
                            "timestamp": "2026-05-27T06:40:00+01:00",
                            "body": "Can someone finally tell me the real ETA?",
                        }
                    ],
                    "copilot": {
                        "summary": "Courier ETA changed twice; close the loop with one confirmed timeline and owner.",
                        "intent": "Fulfillment follow-up",
                        "sentiment": "frustrated",
                        "autoTags": ["eta", "courier", "promise-risk"],
                        "slaReason": "Customer got a timely response but still lacks a trustworthy delivery commitment.",
                        "suggestedReply": "I am confirming the courier scan now and will send one final ETA update within 20 minutes.",
                        "suggestedArticle": "Courier delay playbook",
                        "escalation": "Escalate to Fulfillment if the next courier checkpoint is still missing.",
                        "recommendedAction": "Verify courier checkpoint, then send one firm ETA update.",
                        "confidence": 88,
                    },
                },
                {
                    "id": "conv-1003",
                    "ticketNumber": "OMNI-1003",
                    "customerId": "cust-3",
                    "channelId": "api",
                    "subject": "Partner sync retries spiking",
                    "preview": "Partner webhook retries increased and several confirmations are delayed.",
                    "status": "waiting",
                    "priority": "high",
                    "sentiment": "neutral",
                    "intent": "Partner integration incident",
                    "group": "Engineering",
                    "assigneeId": "agent-5",
                    "createdAt": "2026-05-27T05:50:00+01:00",
                    "updatedAt": "2026-05-27T07:20:00+01:00",
                    "firstResponseDue": "2026-05-27T06:35:00+01:00",
                    "resolutionDue": "2026-05-27T16:00:00+01:00",
                    "slaState": "risk",
                    "language": "English",
                    "unread": True,
                    "tags": ["api", "partner", "incident"],
                    "tasks": [{"id": "task-1003-1", "label": "Review failing webhook traces", "done": False}],
                    "timeline": [
                        {
                            "id": "event-1003-1",
                            "type": "api-event",
                            "channelId": "api",
                            "author": "Partner monitor",
                            "authorRole": "partner",
                            "timestamp": "2026-05-27T05:50:00+01:00",
                            "body": "Retry volume crossed the alert threshold for order confirmation webhooks.",
                        }
                    ],
                    "copilot": {
                        "summary": "This looks like an integration reliability issue with customer impact if confirmations stay delayed.",
                        "intent": "Partner integration incident",
                        "sentiment": "neutral",
                        "autoTags": ["api", "webhook", "incident"],
                        "slaReason": "Customer promises will slip if engineering does not validate the queue quickly.",
                        "suggestedReply": "We are investigating delayed confirmations and will share the next status by 08:00 WAT.",
                        "suggestedArticle": "Partner webhook incident runbook",
                        "escalation": "Keep Engineering as owner and notify Partner Support if backlog grows.",
                        "recommendedAction": "Check the failing webhook traces and confirm whether retries are recoverable.",
                        "confidence": 90,
                    },
                },
            ],
            "handoffs": [
                {
                    "id": "handoff-1001",
                    "conversationId": "conv-1003",
                    "ticketNumber": "OMNI-1003",
                    "customerId": "cust-3",
                    "sourceTeam": "Partner Support",
                    "receivingTeam": "Engineering",
                    "requesterId": "agent-5",
                    "ownerId": "agent-5",
                    "reason": "Partner sync retries need engineering validation.",
                    "context": "Delayed confirmations are affecting order visibility.",
                    "customerImpact": "Enterprise partner cannot confirm customer orders in real time.",
                    "acceptanceCriteria": "Retry cause confirmed and next mitigation path documented.",
                    "status": "in-progress",
                    "priority": "high",
                    "dueAt": "2026-05-27T09:00:00+01:00",
                    "createdAt": "2026-05-27T06:10:00+01:00",
                    "updatedAt": "2026-05-27T07:20:00+01:00",
                    "checklist": [
                        {"id": "handoff-1001-1", "label": "Review failed webhook samples", "done": True},
                        {"id": "handoff-1001-2", "label": "Confirm retry queue depth", "done": False},
                    ],
                    "blockers": ["Need one infra log export from the integration worker."],
                }
            ],
            "knowledge": [
                {
                    "id": "article-1",
                    "title": "Refund trace verification checklist",
                    "category": "Billing",
                    "status": "published",
                    "language": "English",
                    "helpfulness": 92,
                    "deflection": 34,
                    "ownerId": "agent-1",
                    "intents": ["Refund dispute"],
                    "updatedAt": "2026-05-26T18:00:00+01:00",
                },
                {
                    "id": "article-2",
                    "title": "Partner webhook incident runbook",
                    "category": "Integrations",
                    "status": "review",
                    "language": "English",
                    "helpfulness": 80,
                    "deflection": 12,
                    "ownerId": "agent-5",
                    "intents": ["Partner integration incident"],
                    "updatedAt": "2026-05-27T06:30:00+01:00",
                },
            ],
            "automationRules": [
                {
                    "id": "rule-1",
                    "name": "High-risk promise watch",
                    "trigger": "When any ticket has a missed promise or SLA risk",
                    "condition": "Priority is high or urgent",
                    "action": "Move to top of Work Queue and notify the active lead",
                    "owner": "Ops Automation",
                    "status": "active",
                    "health": 96,
                    "lastFired": "2026-05-27T07:05:00+01:00",
                    "failures": 0,
                },
                {
                    "id": "rule-2",
                    "name": "Partner incident handoff",
                    "trigger": "When partner retries exceed threshold",
                    "condition": "Queue depth exceeds 10 failed confirmations",
                    "action": "Open engineering handoff with checklist",
                    "owner": "Platform Ops",
                    "status": "active",
                    "health": 90,
                    "lastFired": "2026-05-27T06:10:00+01:00",
                    "failures": 0,
                },
            ],
            "slaPolicies": [
                {
                    "id": "sla-1",
                    "name": "Priority billing",
                    "channels": ["email", "phone"],
                    "priority": "urgent",
                    "firstResponseMinutes": 30,
                    "resolutionMinutes": 240,
                    "businessHours": "24x7",
                },
                {
                    "id": "sla-2",
                    "name": "Live channels",
                    "channels": ["chat", "whatsapp"],
                    "priority": "high",
                    "firstResponseMinutes": 15,
                    "resolutionMinutes": 480,
                    "businessHours": "24x7",
                },
            ],
            "settings": {"aiWorkQueueAutomationEnabled": True},
            "tracker": {
                "milestoneStatus": "Frontend PWA complete; backend API slice now added locally and awaiting frontend wiring.",
                "epics": [
                    {"id": "E1", "title": "Research and product definition", "status": "done"},
                    {"id": "E2", "title": "Omni data model and app shell", "status": "done"},
                    {"id": "E3", "title": "Omnichannel operations workflow", "status": "done"},
                    {"id": "E4", "title": "Admin, analytics, knowledge, workforce, and tracker", "status": "done"},
                    {"id": "E5", "title": "Install-ready app, verification, and delivery", "status": "done"},
                    {"id": "E6", "title": "Python backend vertical slice", "status": "done"},
                ],
                "backlog": [
                    {"id": "B-019", "title": "SVP-ready operations UI pass", "priority": "P0", "status": "done"},
                    {"id": "B-020", "title": "Default-on AI work queue backend requirement", "priority": "P0", "status": "done"},
                    {"id": "B-021", "title": "Start independent Python backend vertical slice", "priority": "P0", "status": "done"},
                    {"id": "B-022", "title": "Wire frontend PWA to backend APIs", "priority": "P0", "status": "pending"},
                ],
                "closedIssues": [
                    {"id": "C-012", "title": "SVP-ready UI improvement pass completed", "closedOn": "2026-05-26"},
                    {"id": "C-013", "title": "AI work queue automation locked as default-on behavior unless disabled in Setup", "closedOn": "2026-05-27"},
                    {"id": "C-014", "title": "Independent Python backend API slice added with smoke tests and local docs", "closedOn": "2026-05-27"},
                ],
                "pendingItems": [
                    "Choose production hosting target.",
                    "Wire the React PWA to authenticated backend APIs.",
                    "Connect real channel credentials and approved imports when requested.",
                    "Add production auth, RBAC, audit retention, tenant isolation, and attachment scanning.",
                ],
            },
        }
    )
