import type { Channel, CustomerProfile, OmniConversation, OmniState } from './domain'

export const EMPTY_TICKET_ID = 'empty-ticket'
export const EMPTY_CUSTOMER_ID = 'empty-customer'

export const channelPresentation: Partial<
  Record<Channel['id'], Pick<Channel, 'label' | 'shortLabel' | 'targetMinutes' | 'description'>>
> = {
  email: {
    label: 'Email',
    shortLabel: 'Email',
    targetMinutes: 30,
    description: 'Shared support mailboxes and forwarded customer conversations.',
  },
  chat: {
    label: 'Web chat',
    shortLabel: 'Chat',
    targetMinutes: 3,
    description: 'Website conversations and bot escalations.',
  },
  phone: {
    label: 'Phone and voice',
    shortLabel: 'Phone',
    targetMinutes: 5,
    description: 'Calls, callbacks, voicemail, and call summaries.',
  },
  whatsapp: {
    label: 'WhatsApp',
    shortLabel: 'WA',
    targetMinutes: 15,
    description: 'WhatsApp customer conversations.',
  },
  sms: {
    label: 'SMS',
    shortLabel: 'SMS',
    targetMinutes: 30,
    description: 'Inbound and outbound text messages.',
  },
  instagram: {
    label: 'Instagram',
    shortLabel: 'IG',
    targetMinutes: 30,
    description: 'Instagram direct messages and replies.',
  },
  facebook: {
    label: 'Facebook',
    shortLabel: 'FB',
    targetMinutes: 30,
    description: 'Facebook Messenger conversations.',
  },
  portal: {
    label: 'Portal',
    shortLabel: 'Portal',
    targetMinutes: 60,
    description: 'Customer support portal requests.',
  },
  api: {
    label: 'Partner systems',
    shortLabel: 'API',
    targetMinutes: 30,
    description: 'Signed partner and internal system requests.',
  },
  internal: {
    label: 'Internal',
    shortLabel: 'Internal',
    targetMinutes: 60,
    description: 'Internal handoffs and linked work.',
  },
}

const emptyChannel: Channel = {
  id: 'email',
  label: 'Email',
  shortLabel: 'Email',
  status: 'paused',
  queueDepth: 0,
  activeSessions: 0,
  avgWaitMinutes: 0,
  targetMinutes: 30,
  slaRisk: 0,
  health: 0,
  intakeEnabled: false,
  description: 'Not configured.',
  intakeLive: false,
  intakeNote: 'Not configured.',
  outboundLive: false,
  outboundNote: 'Not configured.',
}

const emptyCustomer: CustomerProfile = {
  id: EMPTY_CUSTOMER_ID,
  name: 'No customer selected',
  company: '',
  title: '',
  email: '',
  phone: '',
  location: '',
  healthScore: 0,
  csat: 0,
  totalConversations: 0,
  openValue: '',
  preferredChannels: [],
  contactMethods: [],
  tags: [],
  recentActivity: '',
  timezone: 'Africa/Lagos',
  language: 'English',
  notes: '',
  createdAt: '',
  updatedAt: '',
}

const emptyConversation: OmniConversation = {
  id: EMPTY_TICKET_ID,
  ticketNumber: '',
  customerId: EMPTY_CUSTOMER_ID,
  channelId: 'email',
  subject: 'No ticket selected',
  preview: 'Connect to the Omni API to load the active market workspace.',
  status: 'closed',
  priority: 'low',
  sentiment: 'neutral',
  intent: 'Unavailable',
  group: 'Unassigned',
  assigneeId: '',
  createdAt: '1970-01-01T00:00:00.000Z',
  updatedAt: '1970-01-01T00:00:00.000Z',
  firstResponseDue: '1970-01-01T00:00:00.000Z',
  resolutionDue: '1970-01-01T00:00:00.000Z',
  slaState: 'paused',
  language: 'en',
  unread: false,
  tags: [],
  customFields: {},
  tasks: [],
  timeline: [],
  copilot: {
    summary: '',
    intent: '',
    sentiment: 'neutral',
    autoTags: [],
    slaReason: '',
    suggestedReply: '',
    suggestedArticle: '',
    escalation: '',
    recommendedAction: '',
    confidence: 0,
  },
}

export const initialOmniState: OmniState = {
  version: 21,
  selectedScreen: 'command',
  selectedConversationId: EMPTY_TICKET_ID,
  selectedCustomerId: EMPTY_CUSTOMER_ID,
  selectedChannelId: 'all',
  filters: {
    channel: 'all',
    status: 'all',
    priority: 'all',
    sla: 'all',
    assignee: 'all',
    sentiment: 'all',
    search: '',
  },
  channels: [emptyChannel],
  conversations: [emptyConversation],
  customers: [emptyCustomer],
  agents: [],
  supportGroups: [],
  articles: [],
  ticketFields: [],
  responseMacros: [],
  rules: [],
  slaPolicies: [],
  businessHours: [],
  ticketTemplates: [],
  tags: [],
  csatSurveys: [],
  emailNotifications: [],
  scenarioAutomations: [],
  customFieldDefinitions: [],
  customObjects: [],
  products: [],
  savedReports: [],
  serviceAppointments: [],
  discussionTopics: [],
  handoffs: [],
  cases: [],
  outbox: [],
  settings: { aiWorkQueueAutomationEnabled: false },
  epics: [],
  backlog: [],
  issues: [],
}
