import type {
  AgentProfile,
  AutomationRule,
  BacklogItem,
  Channel,
  CustomerProfile,
  Epic,
  HandoffRecord,
  Issue,
  KnowledgeArticle,
  OmniConversation,
  OmniState,
  ResponseMacro,
  SlaPolicy,
  SupportGroup,
  TicketField,
} from './domain'

const now = '2026-05-25T07:20:00+01:00'

export const seedChannels: Channel[] = [
  {
    id: 'email',
    label: 'Email',
    shortLabel: 'Email',
    status: 'healthy',
    queueDepth: 38,
    activeSessions: 12,
    avgWaitMinutes: 18,
    targetMinutes: 30,
    slaRisk: 5,
    health: 94,
    intakeEnabled: true,
    description: 'Shared support mailboxes and forwarded customer conversations.',
  },
  {
    id: 'chat',
    label: 'Web chat',
    shortLabel: 'Chat',
    status: 'degraded',
    queueDepth: 21,
    activeSessions: 16,
    avgWaitMinutes: 7,
    targetMinutes: 3,
    slaRisk: 9,
    health: 72,
    intakeEnabled: true,
    description: 'Live chat and bot-escalated website conversations.',
  },
  {
    id: 'phone',
    label: 'Phone and voice',
    shortLabel: 'Phone',
    status: 'healthy',
    queueDepth: 11,
    activeSessions: 8,
    avgWaitMinutes: 4,
    targetMinutes: 5,
    slaRisk: 2,
    health: 88,
    intakeEnabled: true,
    description: 'Inbound calls, callbacks, voicemail, and call summaries.',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    shortLabel: 'WA',
    status: 'healthy',
    queueDepth: 32,
    activeSessions: 20,
    avgWaitMinutes: 10,
    targetMinutes: 15,
    slaRisk: 4,
    health: 91,
    intakeEnabled: true,
    description: 'Messaging app conversations with media and template replies.',
  },
  {
    id: 'sms',
    label: 'SMS',
    shortLabel: 'SMS',
    status: 'healthy',
    queueDepth: 16,
    activeSessions: 6,
    avgWaitMinutes: 12,
    targetMinutes: 20,
    slaRisk: 2,
    health: 90,
    intakeEnabled: true,
    description: 'Short-form text updates and verification follow-ups.',
  },
  {
    id: 'instagram',
    label: 'Instagram',
    shortLabel: 'IG',
    status: 'degraded',
    queueDepth: 14,
    activeSessions: 9,
    avgWaitMinutes: 24,
    targetMinutes: 20,
    slaRisk: 6,
    health: 68,
    intakeEnabled: true,
    description: 'Comments and direct messages from Instagram.',
  },
  {
    id: 'facebook',
    label: 'Facebook',
    shortLabel: 'FB',
    status: 'healthy',
    queueDepth: 9,
    activeSessions: 5,
    avgWaitMinutes: 19,
    targetMinutes: 20,
    slaRisk: 1,
    health: 86,
    intakeEnabled: true,
    description: 'Facebook Messenger, page comments, and public post follow-ups.',
  },
  {
    id: 'portal',
    label: 'Customer portal',
    shortLabel: 'Portal',
    status: 'healthy',
    queueDepth: 24,
    activeSessions: 3,
    avgWaitMinutes: 42,
    targetMinutes: 60,
    slaRisk: 3,
    health: 93,
    intakeEnabled: true,
    description: 'Authenticated portal tickets and knowledge deflection.',
  },
  {
    id: 'api',
    label: 'Partner systems',
    shortLabel: 'Partner',
    status: 'healthy',
    queueDepth: 7,
    activeSessions: 4,
    avgWaitMinutes: 28,
    targetMinutes: 45,
    slaRisk: 1,
    health: 97,
    intakeEnabled: true,
    description: 'Partner orders, system alerts, and integration issues.',
  },
  {
    id: 'internal',
    label: 'Internal handoffs',
    shortLabel: 'Internal',
    status: 'paused',
    queueDepth: 12,
    activeSessions: 2,
    avgWaitMinutes: 34,
    targetMinutes: 45,
    slaRisk: 4,
    health: 74,
    intakeEnabled: false,
    description: 'Operations handoffs to billing, logistics, compliance, or engineering.',
  },
]

export const seedAgents: AgentProfile[] = [
  {
    id: 'agent-1',
    name: 'Amara Lee',
    role: 'Omni Agent',
    avatar: 'AL',
    availability: 'available',
    skills: ['Email', 'Portal', 'Billing'],
    load: 11,
    capacity: 16,
    occupancy: 69,
    csat: 94,
    shift: '07:00-15:00',
  },
  {
    id: 'agent-2',
    name: 'Noah Chen',
    role: 'Live Channels Lead',
    avatar: 'NC',
    availability: 'busy',
    skills: ['Chat', 'WhatsApp', 'SMS'],
    load: 18,
    capacity: 20,
    occupancy: 90,
    csat: 91,
    shift: '07:00-15:00',
  },
  {
    id: 'agent-3',
    name: 'Priya Nair',
    role: 'Voice Specialist',
    avatar: 'PN',
    availability: 'available',
    skills: ['Phone', 'Escalations', 'Retention'],
    load: 8,
    capacity: 14,
    occupancy: 57,
    csat: 96,
    shift: '06:00-14:00',
  },
  {
    id: 'agent-4',
    name: 'Mateo Ruiz',
    role: 'Social Support',
    avatar: 'MR',
    availability: 'away',
    skills: ['Instagram', 'Facebook', 'Public replies'],
    load: 13,
    capacity: 15,
    occupancy: 87,
    csat: 88,
    shift: '08:00-16:00',
  },
  {
    id: 'agent-5',
    name: 'Zara Okafor',
    role: 'Partner Support',
    avatar: 'ZO',
    availability: 'available',
    skills: ['Partner systems', 'Internal', 'Engineering handoff'],
    load: 6,
    capacity: 12,
    occupancy: 50,
    csat: 95,
    shift: '07:00-15:00',
  },
]

export const seedSupportGroups: SupportGroup[] = [
  {
    id: 'group-billing',
    name: 'Billing Support',
    description: 'Payment, refund, duplicate charge, and billing recovery ownership.',
    teamEmail: 'billing-support@omniticket.example.com',
    active: true,
    channels: ['email', 'portal', 'api'],
    skills: ['payments', 'refunds', 'billing'],
    memberCount: 1,
    openTicketCount: 2,
    slaRiskCount: 1,
    updatedAt: now,
  },
  {
    id: 'group-chat',
    name: 'Chat Care',
    description: 'Live chat, WhatsApp, SMS, and short-form customer conversations.',
    teamEmail: 'chat-care@omniticket.example.com',
    active: true,
    channels: ['whatsapp', 'sms', 'portal'],
    skills: ['messaging', 'frontline support'],
    memberCount: 1,
    openTicketCount: 1,
    slaRiskCount: 0,
    updatedAt: now,
  },
  {
    id: 'group-social',
    name: 'Social Care',
    description: 'Public social complaints, DMs, and reputation-sensitive replies.',
    teamEmail: 'social-care@omniticket.example.com',
    active: true,
    channels: ['facebook', 'instagram'],
    skills: ['social', 'complaints', 'recovery'],
    memberCount: 1,
    openTicketCount: 1,
    slaRiskCount: 1,
    updatedAt: now,
  },
  {
    id: 'group-escalations',
    name: 'Escalations',
    description: 'VIP, SLA breach, and cross-team recovery operations.',
    teamEmail: 'escalations@omniticket.example.com',
    active: true,
    channels: ['phone', 'internal', 'api'],
    skills: ['vip', 'sla', 'incident'],
    memberCount: 1,
    openTicketCount: 1,
    slaRiskCount: 1,
    updatedAt: now,
  },
  {
    id: 'group-fulfillment',
    name: 'Fulfillment',
    description: 'Booking confirmation, partner fulfillment, and post-booking fixes.',
    teamEmail: 'fulfillment@omniticket.example.com',
    active: true,
    channels: ['email', 'api', 'internal'],
    skills: ['booking', 'partners', 'fulfillment'],
    memberCount: 0,
    openTicketCount: 0,
    slaRiskCount: 0,
    updatedAt: now,
  },
  {
    id: 'group-engineering',
    name: 'Engineering',
    description: 'Platform defects, API issues, and technical incident resolution.',
    teamEmail: 'engineering@omniticket.example.com',
    active: true,
    channels: ['api', 'internal'],
    skills: ['platform', 'api', 'incident'],
    memberCount: 0,
    openTicketCount: 0,
    slaRiskCount: 0,
    updatedAt: now,
  },
  {
    id: 'group-account-ops',
    name: 'Account Operations',
    description: 'Account access, profile corrections, and customer operations.',
    teamEmail: 'account-ops@omniticket.example.com',
    active: true,
    channels: ['email', 'portal', 'phone'],
    skills: ['accounts', 'identity', 'operations'],
    memberCount: 0,
    openTicketCount: 0,
    slaRiskCount: 0,
    updatedAt: now,
  },
  {
    id: 'group-compliance',
    name: 'Compliance',
    description: 'Sensitive customer, audit, retention, and policy review cases.',
    teamEmail: 'compliance@omniticket.example.com',
    active: true,
    channels: ['email', 'internal'],
    skills: ['compliance', 'audit', 'policy'],
    memberCount: 0,
    openTicketCount: 0,
    slaRiskCount: 0,
    updatedAt: now,
  },
]

export const seedCustomers: CustomerProfile[] = [
  {
    id: 'cust-1',
    name: 'Maya Roberts',
    company: 'Northstar Retail',
    title: 'Operations Manager',
    email: 'maya.roberts@example.com',
    phone: '+1 415 555 0187',
    location: 'San Francisco, CA',
    healthScore: 38,
    csat: 3.7,
    totalConversations: 42,
    openValue: '$18.4k',
    preferredChannels: ['email', 'chat'],
    contactMethods: [
      { type: 'email', label: 'Work email', value: 'maya.roberts@example.com', primary: true },
      { type: 'phone', label: 'Mobile', value: '+1 415 555 0187' },
      { type: 'portal', label: 'Portal', value: 'northstar-retail' },
    ],
    tags: ['enterprise', 'sla-watch', 'billing'],
    recentActivity: 'Reopened a billing dispute after two promised callbacks were missed.',
  },
  {
    id: 'cust-2',
    name: 'Leo Ahmed',
    company: 'BrightCart',
    title: 'Store Owner',
    email: 'leo.ahmed@example.com',
    phone: '+44 20 5555 0150',
    location: 'London, UK',
    healthScore: 61,
    csat: 4.1,
    totalConversations: 18,
    openValue: '$4.8k',
    preferredChannels: ['whatsapp', 'sms'],
    contactMethods: [
      { type: 'email', label: 'Work email', value: 'leo.ahmed@example.com' },
      { type: 'whatsapp', label: 'WhatsApp', value: '+44 20 5555 0150', primary: true },
      { type: 'sms', label: 'SMS', value: '+44 20 5555 0150' },
    ],
    tags: ['payments', 'mobile-first'],
    recentActivity: 'Sent screenshots showing duplicate payment capture.',
  },
  {
    id: 'cust-3',
    name: 'Anika Shah',
    company: 'Orbit Labs',
    title: 'Developer Relations',
    email: 'anika.shah@example.com',
    phone: '+91 80 5555 0193',
    location: 'Bengaluru, India',
    healthScore: 72,
    csat: 4.5,
    totalConversations: 27,
    openValue: '$12.1k',
    preferredChannels: ['api', 'portal'],
    contactMethods: [
      { type: 'email', label: 'Developer inbox', value: 'anika.shah@example.com', primary: true },
      { type: 'portal', label: 'Portal', value: 'orbit-labs' },
    ],
    tags: ['partner-systems', 'duplicate-events'],
    recentActivity: 'Shared system traces and asked for duplicate event guidance.',
  },
  {
    id: 'cust-4',
    name: 'Sofia Grant',
    company: 'Solace Home',
    title: 'Customer',
    email: 'sofia.grant@example.com',
    phone: '+1 212 555 0114',
    location: 'New York, NY',
    healthScore: 44,
    csat: 3.9,
    totalConversations: 11,
    openValue: '$820',
    preferredChannels: ['instagram', 'facebook'],
    contactMethods: [
      { type: 'social', label: 'Instagram', value: '@sofiagrant', primary: true },
      { type: 'social', label: 'Facebook', value: 'Sofia Grant' },
      { type: 'email', label: 'Email', value: 'sofia.grant@example.com' },
    ],
    tags: ['delivery-risk', 'reputation-risk'],
    recentActivity: 'Shared order screenshots after a missed delivery complaint.',
  },
  {
    id: 'cust-5',
    name: 'Daniel Moore',
    company: 'Greenline Services',
    title: 'Procurement Lead',
    email: 'daniel.moore@example.com',
    phone: '+1 312 555 0108',
    location: 'Chicago, IL',
    healthScore: 84,
    csat: 4.8,
    totalConversations: 9,
    openValue: '$31.6k',
    preferredChannels: ['phone', 'email'],
    contactMethods: [
      { type: 'phone', label: 'Direct line', value: '+1 312 555 0108', primary: true },
      { type: 'email', label: 'Procurement email', value: 'daniel.moore@example.com' },
    ],
    tags: ['vip', 'phone-preferred'],
    recentActivity: 'Called the renewal desk and asked for same-day confirmation.',
  },
]

export const seedConversations: OmniConversation[] = [
  {
    id: 'conv-1001',
    ticketNumber: 'OMNI-1001',
    customerId: 'cust-1',
    channelId: 'email',
    subject: 'Invoice adjustment was promised but not reflected',
    preview: 'The revised invoice still shows the original disputed charge.',
    status: 'open',
    priority: 'urgent',
    sentiment: 'at-risk',
    intent: 'Billing dispute',
    group: 'Billing Operations',
    assigneeId: 'agent-1',
    createdAt: '2026-05-25T05:40:00+01:00',
    updatedAt: now,
    firstResponseDue: '2026-05-25T07:55:00+01:00',
    resolutionDue: '2026-05-25T10:40:00+01:00',
    slaState: 'risk',
    language: 'English',
    unread: true,
    tags: ['billing', 'enterprise', 'escalation'],
    customFields: {
      booking_reference: 'INV-4471',
      issue_category: 'Payment',
      trip_stage: 'Post-trip',
    },
    tasks: [
      { id: 'task-1001-1', label: 'Confirm adjustment with Finance', done: false },
      { id: 'task-1001-2', label: 'Send corrected invoice', done: false },
      { id: 'task-1001-3', label: 'Schedule supervisor callback', done: true },
    ],
    timeline: [
      {
        id: 'event-1001-1',
        type: 'customer-message',
        channelId: 'email',
        author: 'Maya Roberts',
        authorRole: 'customer',
        timestamp: '2026-05-25T05:40:00+01:00',
        body: 'The invoice still has the disputed charge. I was promised this would be fixed before our finance close.',
      },
      {
        id: 'event-1001-2',
        type: 'automation',
        channelId: 'email',
        author: 'Routing rule',
        authorRole: 'system',
        timestamp: '2026-05-25T05:41:00+01:00',
        body: 'Enterprise account detected. Priority raised to urgent and routed to Billing Operations.',
      },
      {
        id: 'event-1001-3',
        type: 'internal-note',
        channelId: 'internal',
        author: 'Amara Lee',
        authorRole: 'agent',
        timestamp: '2026-05-25T07:10:00+01:00',
        body: 'Finance confirmed adjustment was approved but not posted. Need corrected invoice before 10:00.',
      },
    ],
    copilot: {
      summary: 'Enterprise customer is at risk because a promised invoice correction has not appeared.',
      intent: 'Billing correction and escalation',
      sentiment: 'at-risk',
      autoTags: ['billing', 'enterprise', 'promise-breach'],
      slaReason: 'Resolution due in less than four hours and customer references a missed commitment.',
      suggestedReply:
        'I confirmed the adjustment was approved and I am pushing the corrected invoice through now. I will send the updated copy here and keep this ticket open until you confirm it is correct.',
      suggestedArticle: 'How invoice adjustments are applied',
      escalation: 'Notify Billing Operations lead if corrected invoice is not posted by 09:30.',
      recommendedAction: 'Send reply, keep urgent priority, and create billing handoff.',
      confidence: 92,
    },
  },
  {
    id: 'conv-1002',
    ticketNumber: 'OMNI-1002',
    customerId: 'cust-2',
    channelId: 'whatsapp',
    subject: 'Duplicate payment shown after mobile checkout',
    preview: 'Customer sent screenshots showing two payment holds.',
    status: 'pending',
    priority: 'high',
    sentiment: 'frustrated',
    intent: 'Payment duplicate',
    group: 'Payments',
    assigneeId: 'agent-2',
    createdAt: '2026-05-25T06:15:00+01:00',
    updatedAt: '2026-05-25T07:05:00+01:00',
    firstResponseDue: '2026-05-25T06:30:00+01:00',
    resolutionDue: '2026-05-25T12:15:00+01:00',
    slaState: 'healthy',
    language: 'English',
    unread: false,
    tags: ['payments', 'whatsapp', 'duplicate-hold'],
    customFields: {
      booking_reference: 'PAY-2291',
      issue_category: 'Payment',
      trip_stage: 'Pre-trip',
    },
    tasks: [
      { id: 'task-1002-1', label: 'Check payment gateway references', done: true },
      { id: 'task-1002-2', label: 'Send release confirmation', done: false },
    ],
    timeline: [
      {
        id: 'event-1002-1',
        type: 'customer-message',
        channelId: 'whatsapp',
        author: 'Leo Ahmed',
        authorRole: 'customer',
        timestamp: '2026-05-25T06:15:00+01:00',
        body: 'I have two payment holds for one order. Screenshots attached.',
      },
      {
        id: 'event-1002-2',
        type: 'agent-reply',
        channelId: 'whatsapp',
        author: 'Noah Chen',
        authorRole: 'agent',
        timestamp: '2026-05-25T06:22:00+01:00',
        body: 'I am checking both references now and will confirm which one will be released.',
      },
    ],
    copilot: {
      summary: 'Customer sees duplicate holds after mobile checkout and needs release confirmation.',
      intent: 'Payment verification',
      sentiment: 'frustrated',
      autoTags: ['payments', 'mobile', 'duplicate-hold'],
      slaReason: 'On time, but mobile payment issues can quickly frustrate customers.',
      suggestedReply:
        'I found one successful payment and one authorization hold. The hold should release automatically, and I am sending the payment reference to our processor for confirmation.',
      suggestedArticle: 'Why a card authorization can appear twice',
      escalation: 'Escalate to Payments if hold is not released within processor window.',
      recommendedAction: 'Send status reply and keep pending until processor confirmation.',
      confidence: 89,
    },
  },
  {
    id: 'conv-1003',
    ticketNumber: 'OMNI-1003',
    customerId: 'cust-3',
    channelId: 'api',
    subject: 'Partner system created duplicate order events',
    preview: 'Partner system is receiving duplicate order updates.',
    status: 'open',
    priority: 'high',
    sentiment: 'neutral',
    intent: 'Partner system incident',
    group: 'Platform Support',
    assigneeId: 'agent-5',
    createdAt: '2026-05-24T16:30:00+01:00',
    updatedAt: '2026-05-25T06:50:00+01:00',
    firstResponseDue: '2026-05-24T17:15:00+01:00',
    resolutionDue: '2026-05-25T14:30:00+01:00',
    slaState: 'healthy',
    language: 'English',
    unread: false,
    tags: ['partner-system', 'duplicate-event', 'partner'],
    customFields: {},
    tasks: [
      { id: 'task-1003-1', label: 'Compare event ids in replay logs', done: true },
      { id: 'task-1003-2', label: 'Publish duplicate-event handling recommendation', done: false },
    ],
    timeline: [
      {
        id: 'event-1003-1',
        type: 'api-event',
        channelId: 'api',
        author: 'Partner system',
        authorRole: 'partner',
        timestamp: '2026-05-24T16:30:00+01:00',
        body: 'order.updated delivered twice for orders 7781 and 7789 after replay.',
      },
      {
        id: 'event-1003-2',
        type: 'internal-note',
        channelId: 'internal',
        author: 'Zara Okafor',
        authorRole: 'agent',
        timestamp: '2026-05-25T06:50:00+01:00',
        body: 'Engineering says replay queue did not dedupe retries during deployment window.',
      },
    ],
    copilot: {
      summary: 'Partner reports duplicate order updates after a replay during a deployment window.',
      intent: 'Duplicate event analysis',
      sentiment: 'neutral',
      autoTags: ['partner-system', 'duplicate-event', 'replay'],
      slaReason: 'On time, but partner impact requires clear mitigation guidance.',
      suggestedReply:
        'We traced the duplicates to replay retries during the deployment window. Please dedupe on event_id while we complete the replay guard update; I will share the final incident note today.',
      suggestedArticle: 'Duplicate event handling for partner systems',
      escalation: 'Keep Platform Support and Engineering linked until final incident note is sent.',
      recommendedAction: 'Send interim incident note, attach duplicate-event guidance, and keep ticket open.',
      confidence: 86,
    },
  },
  {
    id: 'conv-1004',
    ticketNumber: 'OMNI-1004',
    customerId: 'cust-4',
    channelId: 'instagram',
    subject: 'Public complaint about missed delivery',
    preview: 'Customer posted publicly and sent order screenshots by DM.',
    status: 'new',
    priority: 'urgent',
    sentiment: 'at-risk',
    intent: 'Social escalation',
    group: 'Social Care',
    assigneeId: 'agent-4',
    createdAt: '2026-05-25T07:02:00+01:00',
    updatedAt: '2026-05-25T07:18:00+01:00',
    firstResponseDue: '2026-05-25T07:22:00+01:00',
    resolutionDue: '2026-05-25T11:02:00+01:00',
    slaState: 'breached',
    language: 'English',
    unread: true,
    tags: ['social', 'public-comment', 'delivery'],
    customFields: {
      booking_reference: 'DEL-9042',
      issue_category: 'Baggage',
      trip_stage: 'Post-trip',
    },
    tasks: [
      { id: 'task-1004-1', label: 'Acknowledge public comment', done: false },
      { id: 'task-1004-2', label: 'Move details to private DM', done: true },
      { id: 'task-1004-3', label: 'Handoff to fulfillment', done: false },
    ],
    timeline: [
      {
        id: 'event-1004-1',
        type: 'social-dm',
        channelId: 'instagram',
        author: 'Sofia Grant',
        authorRole: 'customer',
        timestamp: '2026-05-25T07:02:00+01:00',
        body: 'I posted because nobody responded. My delivery is still missing and I need an update today.',
      },
      {
        id: 'event-1004-2',
        type: 'automation',
        channelId: 'instagram',
        author: 'Social escalation detector',
        authorRole: 'system',
        timestamp: '2026-05-25T07:03:00+01:00',
        body: 'Public complaint detected. Priority raised and Social Care notified.',
      },
    ],
    copilot: {
      summary: 'Public social complaint is now in DM and the first response promise is overdue.',
      intent: 'Delivery escalation and reputation risk',
      sentiment: 'at-risk',
      autoTags: ['social-escalation', 'public-complaint', 'delivery'],
      slaReason: 'First response timer has breached and channel health is degraded.',
      suggestedReply:
        'I am sorry this took a public post to get attention. I have your order details from DM and am escalating this to fulfillment now. I will keep the public thread general and update you privately here.',
      suggestedArticle: 'Social complaint handling playbook',
      escalation: 'Handoff to fulfillment and alert supervisor due to public channel risk.',
      recommendedAction: 'Reply in DM, acknowledge public comment, and create fulfillment handoff.',
      confidence: 94,
    },
  },
  {
    id: 'conv-1005',
    ticketNumber: 'OMNI-1005',
    customerId: 'cust-5',
    channelId: 'phone',
    subject: 'Procurement renewal callback requested',
    preview: 'VIP customer called asking for same-day renewal confirmation.',
    status: 'waiting',
    priority: 'medium',
    sentiment: 'positive',
    intent: 'Renewal callback',
    group: 'Account Operations',
    assigneeId: 'agent-3',
    createdAt: '2026-05-25T06:05:00+01:00',
    updatedAt: '2026-05-25T06:45:00+01:00',
    firstResponseDue: '2026-05-25T06:10:00+01:00',
    resolutionDue: '2026-05-26T06:05:00+01:00',
    slaState: 'healthy',
    language: 'English',
    unread: false,
    tags: ['vip', 'renewal', 'callback'],
    customFields: {},
    tasks: [
      { id: 'task-1005-1', label: 'Confirm renewal quote', done: true },
      { id: 'task-1005-2', label: 'Call customer before 13:00', done: false },
    ],
    timeline: [
      {
        id: 'event-1005-1',
        type: 'voice-log',
        channelId: 'phone',
        author: 'Daniel Moore',
        authorRole: 'customer',
        timestamp: '2026-05-25T06:05:00+01:00',
        body: 'Call summary: customer wants same-day confirmation before internal procurement meeting.',
      },
      {
        id: 'event-1005-2',
        type: 'internal-note',
        channelId: 'internal',
        author: 'Priya Nair',
        authorRole: 'agent',
        timestamp: '2026-05-25T06:45:00+01:00',
        body: 'Quote approved. Waiting for account owner to confirm final term.',
      },
    ],
    copilot: {
      summary: 'VIP renewal customer needs a callback before an internal meeting.',
      intent: 'Renewal confirmation',
      sentiment: 'positive',
      autoTags: ['vip', 'renewal', 'callback'],
      slaReason: 'Resolution promise is on track, but the callback commitment is time-specific.',
      suggestedReply:
        'Your renewal quote is approved. I am confirming the final term with the account owner and will call you before 13:00 as requested.',
      suggestedArticle: 'Renewal confirmation checklist',
      escalation: 'Escalate to Account Operations if owner confirmation is not received by 12:00.',
      recommendedAction: 'Keep waiting status and schedule callback task.',
      confidence: 90,
    },
  },
  {
    id: 'conv-1006',
    ticketNumber: 'OMNI-1006',
    customerId: 'cust-1',
    channelId: 'chat',
    subject: 'Portal user cannot add teammates',
    preview: 'Live chat escalated from bot after permissions loop.',
    status: 'open',
    priority: 'medium',
    sentiment: 'neutral',
    intent: 'User management',
    group: 'Access Support',
    assigneeId: 'agent-2',
    createdAt: '2026-05-25T06:55:00+01:00',
    updatedAt: '2026-05-25T07:12:00+01:00',
    firstResponseDue: '2026-05-25T06:58:00+01:00',
    resolutionDue: '2026-05-25T18:55:00+01:00',
    slaState: 'healthy',
    language: 'English',
    unread: false,
    tags: ['access', 'portal', 'chat'],
    customFields: {
      issue_category: 'Portal access',
    },
    tasks: [
      { id: 'task-1006-1', label: 'Review role permissions', done: true },
      { id: 'task-1006-2', label: 'Send admin steps', done: false },
    ],
    timeline: [
      {
        id: 'event-1006-1',
        type: 'chat-transcript',
        channelId: 'chat',
        author: 'Bot handoff',
        authorRole: 'system',
        timestamp: '2026-05-25T06:55:00+01:00',
        body: 'Bot could not resolve teammate invite issue after three permission checks.',
      },
      {
        id: 'event-1006-2',
        type: 'customer-message',
        channelId: 'chat',
        author: 'Maya Roberts',
        authorRole: 'customer',
        timestamp: '2026-05-25T06:56:00+01:00',
        body: 'I need to add our finance users today, but the invite button is disabled.',
      },
    ],
    copilot: {
      summary: 'Portal admin cannot invite teammates because role permissions are blocking the button.',
      intent: 'Access management',
      sentiment: 'neutral',
      autoTags: ['access', 'portal-admin', 'chat-handoff'],
      slaReason: 'Live chat first response target met; resolution is still healthy.',
      suggestedReply:
        'The invite button is disabled because your current role is Billing Manager, not Account Admin. I can send the admin steps or route this to your account owner for a role update.',
      suggestedArticle: 'Managing portal users and roles',
      escalation: 'Escalate only if customer requests account-owner override.',
      recommendedAction: 'Send article and offer role update handoff.',
      confidence: 88,
    },
  },
  {
    id: 'conv-1007',
    ticketNumber: 'OMNI-1007',
    customerId: 'cust-4',
    channelId: 'facebook',
    subject: 'Messenger follow-up on public delivery complaint',
    preview: 'Customer moved from page comment into Facebook Messenger for order details.',
    status: 'open',
    priority: 'high',
    sentiment: 'frustrated',
    intent: 'Social Messenger escalation',
    group: 'Social Care',
    assigneeId: 'agent-4',
    createdAt: '2026-05-25T07:09:00+01:00',
    updatedAt: '2026-05-25T07:24:00+01:00',
    firstResponseDue: '2026-05-25T07:29:00+01:00',
    resolutionDue: '2026-05-25T13:09:00+01:00',
    slaState: 'risk',
    language: 'English',
    unread: true,
    tags: ['facebook', 'messenger', 'delivery'],
    customFields: {
      booking_reference: 'DEL-9042',
      issue_category: 'Baggage',
      trip_stage: 'Post-trip',
    },
    tasks: [
      { id: 'task-1007-1', label: 'Confirm order reference from Messenger', done: true },
      { id: 'task-1007-2', label: 'Post neutral public acknowledgement', done: false },
    ],
    timeline: [
      {
        id: 'event-1007-1',
        type: 'social-dm',
        channelId: 'facebook',
        author: 'Sofia Grant',
        authorRole: 'customer',
        timestamp: '2026-05-25T07:09:00+01:00',
        body: 'I sent the order number here. Please do not ask for private details on the public post.',
      },
      {
        id: 'event-1007-2',
        type: 'agent-reply',
        channelId: 'facebook',
        author: 'Mateo Ruiz',
        authorRole: 'agent',
        timestamp: '2026-05-25T07:16:00+01:00',
        body: 'Thanks for moving the details into Messenger. I have the order number and am checking fulfillment now.',
      },
    ],
    copilot: {
      summary: 'Facebook Messenger thread carries private order details linked to a public complaint.',
      intent: 'Private social follow-up',
      sentiment: 'frustrated',
      autoTags: ['facebook', 'messenger', 'public-complaint'],
      slaReason: 'Social response is still inside target, but sentiment is worsening.',
      suggestedReply:
        'I have the order details here in Messenger. I will keep the public thread general and update you privately as soon as fulfillment confirms the next step.',
      suggestedArticle: 'Social complaint handling playbook',
      escalation: 'Keep Social Care owner assigned and notify fulfillment if no update arrives within 20 minutes.',
      recommendedAction: 'Reply in Messenger and keep the public acknowledgement neutral.',
      confidence: 91,
    },
  },
]

export const seedArticles: KnowledgeArticle[] = [
  {
    id: 'KA-301',
    title: 'How invoice adjustments are applied',
    category: 'Billing',
    status: 'published',
    language: 'English',
    helpfulness: 92,
    deflection: 34,
    ownerId: 'agent-1',
    intents: ['Billing dispute', 'Invoice correction'],
    updatedAt: '2026-05-20T12:00:00+01:00',
  },
  {
    id: 'KA-302',
    title: 'Why a card authorization can appear twice',
    category: 'Payments',
    status: 'published',
    language: 'English',
    helpfulness: 88,
    deflection: 29,
    ownerId: 'agent-2',
    intents: ['Payment duplicate', 'Payment verification'],
    updatedAt: '2026-05-22T09:00:00+01:00',
  },
  {
    id: 'KA-303',
    title: 'Duplicate event handling for partner systems',
    category: 'Partner Systems',
    status: 'review',
    language: 'English',
    helpfulness: 81,
    deflection: 17,
    ownerId: 'agent-5',
    intents: ['Partner system incident', 'Duplicate event analysis'],
    updatedAt: '2026-05-24T18:00:00+01:00',
  },
  {
    id: 'KA-304',
    title: 'Social complaint handling playbook',
    category: 'Social Care',
    status: 'draft',
    language: 'English',
    helpfulness: 73,
    deflection: 8,
    ownerId: 'agent-4',
    intents: ['Social escalation', 'Delivery escalation'],
    updatedAt: '2026-05-25T06:30:00+01:00',
  },
  {
    id: 'KA-305',
    title: 'Managing portal users and roles',
    category: 'Access',
    status: 'published',
    language: 'English',
    helpfulness: 90,
    deflection: 26,
    ownerId: 'agent-2',
    intents: ['User management', 'Access management'],
    updatedAt: '2026-05-18T11:10:00+01:00',
  },
]

export const seedRules: AutomationRule[] = [
  {
    id: 'AUTO-01',
    name: 'Enterprise invoice breach guard',
    trigger: 'Ticket created or updated',
    condition: 'Enterprise customer + billing dispute + at-risk promise',
    action: 'Set urgent priority, route Billing Operations, notify supervisor',
    owner: 'Support Ops',
    status: 'active',
    health: 96,
    lastFired: '2026-05-25T05:41:00+01:00',
    failures: 0,
  },
  {
    id: 'AUTO-02',
    name: 'Social public complaint escalation',
    trigger: 'Social DM or public comment received',
    condition: 'Sentiment at-risk or public complaint tag',
    action: 'Raise priority, assign Social Care, add public-response task',
    owner: 'Social Care',
    status: 'active',
    health: 84,
    lastFired: '2026-05-25T07:03:00+01:00',
    failures: 1,
  },
  {
    id: 'AUTO-03',
    name: 'Partner system router',
    trigger: 'Partner system ticket created',
    condition: 'Duplicate order or integration issue',
    action: 'Assign Platform Support and attach partner troubleshooting article',
    owner: 'Platform Support',
    status: 'active',
    health: 98,
    lastFired: '2026-05-24T16:31:00+01:00',
    failures: 0,
  },
  {
    id: 'AUTO-04',
    name: 'Dormant waiting follow-up',
    trigger: 'Time-based check',
    condition: 'Waiting status for more than 36 hours',
    action: 'Send follow-up macro and schedule closure review',
    owner: 'Customer Care',
    status: 'paused',
    health: 77,
    lastFired: '2026-05-23T14:00:00+01:00',
    failures: 0,
  },
]

export const seedSlaPolicies: SlaPolicy[] = [
  {
    id: 'SLA-1',
    name: 'Urgent customer response',
    active: true,
    channels: ['email', 'chat', 'phone', 'whatsapp', 'instagram', 'facebook'],
    priority: 'urgent',
    firstResponseMinutes: 15,
    resolutionMinutes: 240,
    businessHours: '24x7',
    position: 10,
    updatedAt: '2026-05-24T09:00:00+01:00',
  },
  {
    id: 'SLA-2',
    name: 'Live channel standard',
    active: true,
    channels: ['chat', 'phone', 'whatsapp', 'sms'],
    priority: 'high',
    firstResponseMinutes: 5,
    resolutionMinutes: 360,
    businessHours: '24x7',
    position: 20,
    updatedAt: '2026-05-24T09:00:00+01:00',
  },
  {
    id: 'SLA-3',
    name: 'Portal and partner systems standard',
    active: true,
    channels: ['portal', 'api', 'email'],
    priority: 'medium',
    firstResponseMinutes: 60,
    resolutionMinutes: 1440,
    businessHours: 'Business hours',
    position: 30,
    updatedAt: '2026-05-24T09:00:00+01:00',
  },
]

export const seedTicketFields: TicketField[] = [
  {
    id: 'field-booking-reference',
    key: 'booking_reference',
    label: 'Booking reference',
    fieldType: 'text',
    required: false,
    active: true,
    system: false,
    options: [],
    channels: ['email', 'portal', 'api'],
    placeholder: 'PNR or order ID',
    helpText: 'Use this to link support work to a booking, order, or invoice.',
    position: 10,
    updatedAt: now,
  },
  {
    id: 'field-issue-category',
    key: 'issue_category',
    label: 'Issue category',
    fieldType: 'select',
    required: false,
    active: true,
    system: false,
    options: ['Booking', 'Payment', 'Refund', 'Baggage', 'Portal access'],
    channels: [],
    placeholder: '',
    helpText: 'Keeps routing, reporting, and handoff context consistent.',
    position: 20,
    updatedAt: now,
  },
  {
    id: 'field-trip-stage',
    key: 'trip_stage',
    label: 'Trip stage',
    fieldType: 'select',
    required: false,
    active: true,
    system: false,
    options: ['Pre-trip', 'In-trip', 'Post-trip'],
    channels: ['email', 'whatsapp', 'sms', 'portal'],
    placeholder: '',
    helpText: 'Helps agents separate pre-trip service from recovery work.',
    position: 30,
    updatedAt: now,
  },
]

export const seedHandoffs: HandoffRecord[] = [
  {
    id: 'HO-1001',
    conversationId: 'conv-1001',
    ticketNumber: 'OMNI-1001',
    customerId: 'cust-1',
    sourceTeam: 'Customer Care',
    receivingTeam: 'Billing Operations',
    requesterId: 'agent-1',
    ownerId: 'agent-1',
    reason: 'Invoice correction requires finance approval before customer close.',
    context: 'Enterprise customer was promised a corrected invoice. Finance needs to confirm the disputed charge removal and issue the updated invoice.',
    customerImpact: 'Customer finance close is blocked and relationship is at risk.',
    acceptanceCriteria: 'Finance confirms adjustment, corrected invoice is attached, and agent can send a final public update.',
    status: 'accepted',
    priority: 'urgent',
    dueAt: '2026-05-25T09:30:00+01:00',
    createdAt: '2026-05-25T06:00:00+01:00',
    updatedAt: '2026-05-25T06:35:00+01:00',
    checklist: [
      { id: 'ho-1001-1', label: 'Validate disputed charge and adjustment code', done: true },
      { id: 'ho-1001-2', label: 'Attach corrected invoice to the ticket', done: false },
      { id: 'ho-1001-3', label: 'Confirm customer-facing resolution wording', done: false },
    ],
    blockers: [],
  },
  {
    id: 'HO-1004',
    conversationId: 'conv-1004',
    ticketNumber: 'OMNI-1004',
    customerId: 'cust-4',
    sourceTeam: 'Social Care',
    receivingTeam: 'Fulfillment',
    requesterId: 'agent-4',
    ownerId: 'agent-5',
    reason: 'Public social complaint needs delivery trace and recovery plan.',
    context: 'Customer posted publicly after a missed delivery and moved details into DM. Social Care needs fulfillment status before replying with a concrete next step.',
    customerImpact: 'Public reputation risk and overdue first response promise.',
    acceptanceCriteria: 'Fulfillment confirms location, recovery action, owner, and next customer update time.',
    status: 'requested',
    priority: 'urgent',
    dueAt: '2026-05-25T08:00:00+01:00',
    createdAt: '2026-05-25T07:05:00+01:00',
    updatedAt: '2026-05-25T07:18:00+01:00',
    checklist: [
      { id: 'ho-1004-1', label: 'Confirm last-mile delivery status', done: false },
      { id: 'ho-1004-2', label: 'Approve public acknowledgement wording', done: true },
      { id: 'ho-1004-3', label: 'Share recovery ETA in private DM', done: false },
    ],
    blockers: ['Waiting for fulfillment dispatcher confirmation.'],
  },
  {
    id: 'HO-1003',
    conversationId: 'conv-1003',
    ticketNumber: 'OMNI-1003',
    customerId: 'cust-3',
    sourceTeam: 'Platform Support',
    receivingTeam: 'Engineering',
    requesterId: 'agent-5',
    ownerId: 'agent-5',
    reason: 'Partner system replay needs engineering incident note and guardrail ETA.',
    context: 'Partner received duplicate order updates after replay. Support needs final incident note plus mitigation guidance.',
    customerImpact: 'Partner integration team is manually deduping production events.',
    acceptanceCriteria: 'Engineering supplies incident note, event-id guidance, and replay guard deployment ETA.',
    status: 'in-progress',
    priority: 'high',
    dueAt: '2026-05-25T14:00:00+01:00',
    createdAt: '2026-05-24T17:00:00+01:00',
    updatedAt: '2026-05-25T06:50:00+01:00',
    checklist: [
      { id: 'ho-1003-1', label: 'Compare replay logs with partner samples', done: true },
      { id: 'ho-1003-2', label: 'Draft incident note for support review', done: false },
      { id: 'ho-1003-3', label: 'Confirm deployment ETA for replay guard', done: false },
    ],
    blockers: [],
  },
  {
    id: 'HO-1005',
    conversationId: 'conv-1005',
    ticketNumber: 'OMNI-1005',
    customerId: 'cust-5',
    sourceTeam: 'Voice Support',
    receivingTeam: 'Account Operations',
    requesterId: 'agent-3',
    ownerId: 'agent-1',
    reason: 'VIP renewal callback requires account-owner confirmation.',
    context: 'Customer called ahead of an internal procurement meeting and needs same-day renewal confirmation.',
    customerImpact: 'Renewal decision may slip without confirmed commercial terms.',
    acceptanceCriteria: 'Account Operations confirms final term and callback-ready wording.',
    status: 'blocked',
    priority: 'medium',
    dueAt: '2026-05-25T12:00:00+01:00',
    createdAt: '2026-05-25T06:35:00+01:00',
    updatedAt: '2026-05-25T07:10:00+01:00',
    checklist: [
      { id: 'ho-1005-1', label: 'Validate approved renewal quote', done: true },
      { id: 'ho-1005-2', label: 'Confirm final term with account owner', done: false },
      { id: 'ho-1005-3', label: 'Schedule callback before procurement meeting', done: false },
    ],
    blockers: ['Account owner is in a customer meeting until 11:30.'],
  },
]

export const seedEpics: Epic[] = [
  {
    id: 'E1',
    title: 'Research and product definition',
    outcome: 'Omni support desk transition research, UI plan, architecture, and tracker docs',
    status: 'done',
    pending: 'None',
    progress: 100,
  },
  {
    id: 'E2',
    title: 'Omni data model and app shell',
    outcome: 'Split TypeScript domain, seed data, store, navigation, and IndexedDB persistence',
    status: 'done',
    pending: 'None',
    progress: 100,
  },
  {
    id: 'E3',
    title: 'Omnichannel operations workflow',
    outcome: 'Command Center, Work Queue, Channel Chats, Customer 360, composer, and assistive guidance',
    status: 'done',
    pending: 'None',
    progress: 100,
  },
  {
    id: 'E4',
    title: 'Admin, analytics, knowledge, workforce, and tracker',
    outcome: 'Operational management screens with meaningful data and controls',
    status: 'done',
    pending: 'None',
    progress: 100,
  },
  {
    id: 'E5',
    title: 'Install-ready app, verification, and delivery',
    outcome: 'Offline state, app shell, responsive verification, and milestone emails',
    status: 'done',
    pending: 'None',
    progress: 100,
  },
  {
    id: 'E6',
    title: 'Python backend vertical slice',
    outcome: 'Durable API, worker, Pulse VM deployment, frontend write-through bridge, local TOTP MFA, custom permission profiles, OIDC SSO provider boundary, IMAP email intake, SMTP email delivery, IMAP attachment capture, provider callback boundaries, analytics rollups, CSAT feedback, operational alert controls, attachment/storage governance, ticket fields, response macros, backend-ranked suggestions, duplicate ticket suggestions and merge, public portal intake, public portal ticket follow-up, public portal attachments, market-scoped support groups, handoff-forward emails, linked handoff team tickets, threaded handoff email replies, threaded customer email replies, audited handoff attachment links, production account-request pack, backend-queued account-request email, non-secret account-reference tracking, production launch readiness checklist, and backend global search',
    status: 'in-progress',
    pending: 'Provision external OIDC provider credentials, alert destination account, external dashboards/APM, channel provider credentials, and managed storage/scanner accounts flagged by the readiness checklist',
    progress: 99,
  },
]

export const seedBacklog: BacklogItem[] = [
  { id: 'B-001', title: 'Refresh source support-desk research for omnichannel operations', priority: 'P0', status: 'done', epicId: 'E1' },
  { id: 'B-002', title: 'Rewrite comprehensive UI plan', priority: 'P0', status: 'done', epicId: 'E1' },
  { id: 'B-003', title: 'Rewrite building architecture', priority: 'P0', status: 'done', epicId: 'E1' },
  { id: 'B-004', title: 'Update progress automation to gbolahans@wakanow.com', priority: 'P0', status: 'done', epicId: 'E1' },
  { id: 'B-005', title: 'Add IndexedDB persistence dependency', priority: 'P0', status: 'done', epicId: 'E2' },
  { id: 'B-006', title: 'Create src/domain.ts', priority: 'P0', status: 'done', epicId: 'E2' },
  { id: 'B-007', title: 'Create realistic omnichannel seed data', priority: 'P0', status: 'done', epicId: 'E2' },
  { id: 'B-008', title: 'Create local-first store and derived metrics', priority: 'P0', status: 'done', epicId: 'E2' },
  { id: 'B-009', title: 'Rebuild app shell and navigation', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-010', title: 'Build Omni Command screen', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-011', title: 'Build Unified Inbox and conversation cockpit', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-012', title: 'Add reply, note, handoff, macros, translation, and offline outbox UX', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-013', title: 'Build Live Channels and Customers screens', priority: 'P1', status: 'done', epicId: 'E3' },
  { id: 'B-014', title: 'Build Knowledge, Automation, Analytics, Workforce, Admin, and Tracker screens', priority: 'P1', status: 'done', epicId: 'E4' },
  { id: 'B-015', title: 'Update PWA manifest and service worker', priority: 'P0', status: 'done', epicId: 'E5' },
  { id: 'B-016', title: 'Run lint, build, desktop browser verification, mobile browser verification, and install-readiness checks', priority: 'P0', status: 'done', epicId: 'E5' },
  { id: 'B-017', title: 'Send milestone and final emails; include tracker inline when attachment upload fails', priority: 'P0', status: 'done', epicId: 'E5' },
  { id: 'B-018', title: 'Create structured internal handoff queue and lifecycle', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-019', title: 'Add SVP-ready operations UI pass with priority queue, ticket operating strip, and resolution plan', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-020', title: 'Set AI work queue automation as default-on backend requirement with admin off switch', priority: 'P0', status: 'done', epicId: 'E3' },
  { id: 'B-021', title: 'Start independent Python backend with ticket, customer, connector, handoff, analytics, and settings APIs', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-022', title: 'Wire the frontend PWA to the new Python backend API', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-064', title: 'Add database-backed operational alerts with supervisor/admin APIs', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-065', title: 'Wire operational alerts into Command Center and Setup with acknowledge and resolve actions', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-066', title: 'Add durable alert delivery attempts and webhook dispatch status visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-067', title: 'Add SMTP email outbound adapter and Setup provider-readiness visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-068', title: 'Add durable hourly analytics rollups and Insights backend history panel', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-069', title: 'Add database-backed CSAT feedback with analytics and Insights visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-070', title: 'Add configurable IMAP email inbound sync and Setup readiness visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-071', title: 'Add configurable SMS HTTP outbound adapter and Setup readiness visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-072', title: 'Add signed SMS inbound text and delivery-receipt callback handling', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-073', title: 'Add WhatsApp Cloud API outbound adapter and signed inbound/status callbacks', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-074', title: 'Add Facebook Messenger Graph API outbound adapter and signed inbound/delivery callbacks', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-075', title: 'Add Instagram DM Graph API outbound adapter and signed inbound/read callbacks', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-076', title: 'Add voice HTTP callback adapter and signed call/status callbacks', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-077', title: 'Add database-backed local TOTP MFA enrollment, login enforcement, and Setup controls', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-078', title: 'Add database-backed custom permission profiles and allow/deny overrides', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-079', title: 'Add audit CSV/JSON export, retention policy, admin pruning, worker pruning, and Setup controls', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-080', title: 'Add attachment lifecycle retention, delete/purge, worker cleanup, and Setup controls', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-081', title: 'Add S3-compatible attachment storage, external scanner, pre-storage blocking, and Setup readiness', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-082', title: 'Add OIDC SSO readiness, PKCE start, one-time callback state, user linking, and Login/Setup visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-083', title: 'Add production customer and ticket list search, sort, pagination headers, and filters', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-084', title: 'Add ETag and If-Match optimistic concurrency guards for core records', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-085', title: 'Add backend-ranked knowledge suggestions with reasons and Agent Assist visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-086', title: 'Add durable response macros with ranking, usage tracking, audit history, and composer visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-087', title: 'Add configurable ticket fields with validation, persistence, Setup builder, and form rendering', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-088', title: 'Declutter Setup into focused People, Ticket forms, Governance, Connectors, and Automation sections', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-089', title: 'Add public portal answer deflection and unauthenticated ticket intake', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-090', title: 'Add public portal ticket status lookup and customer reply/reopen flow', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-091', title: 'Add market-scoped support groups with Setup management and handoff routing choices', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-092', title: 'Add market-scoped SLA policies with backend CRUD and Setup management', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-093', title: 'Add Anthropic Messages guidance with AI_Key handling and production identity migration', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-094', title: 'Add database-backed email setup for IMAP intake and SMTP replies', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-095', title: 'Add database-backed production credentials for AI, alerts, SMS, voice, WhatsApp, Facebook, and Instagram', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-096', title: 'Add backend-ranked supervisor recommendations for handoffs, queue pressure, and reassignment', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-097', title: 'Add support-group team inboxes and handoff-forward email queueing with full case context', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-098', title: 'Add backend global search and topbar result routing across operational records', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-099', title: 'Create linked internal team tickets for every handoff and expose the team ticket action', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-100', title: 'Add sanitized production account-request pack and gbolahans email draft', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-101', title: 'Queue sanitized production account-request email through the durable outbound pipeline', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-102', title: 'Add non-secret production account-reference tracking and API_DOCS snippet generation', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-103', title: 'Add production launch readiness checklist with live evidence and provider gates', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-104', title: 'Thread handoff-forward email replies back into linked internal tickets', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-105', title: 'Thread customer email replies back into the original ticket with reopen and audit history', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-106', title: 'Add audited signed attachment links to handoff-forward emails', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-107', title: 'Capture IMAP email attachments through ticket attachment scanning and storage', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-108', title: 'Add public portal attachment uploads and sanitized customer attachment visibility', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-109', title: 'Add backend-ranked duplicate ticket suggestions and audited merge controls', priority: 'P0', status: 'done', epicId: 'E6' },
  { id: 'B-110', title: 'Omni parity dashboard: ticket/chat trends, CSAT, agents, filters, todo, and activity', priority: 'P0', status: 'pending', epicId: 'E6' },
  { id: 'B-111', title: 'Omni parity tickets: views, export, filters, inline assign, shortcuts, threads, linked tickets, tasks, time logs, and AHT', priority: 'P0', status: 'pending', epicId: 'E6' },
  { id: 'B-112', title: 'Omni parity admin: AI, team, channels, workflows, productivity, security, and notifications modules', priority: 'P0', status: 'pending', epicId: 'E6' },
  { id: 'B-113', title: 'Omni parity operations: forums, campaigns, custom objects, products, field service, exports, and branding', priority: 'P0', status: 'pending', epicId: 'E6' },
  { id: 'B-114', title: 'Omni parity analytics: report catalog, saved reports, exports, and scheduled reports', priority: 'P0', status: 'pending', epicId: 'E6' },
  { id: 'B-115', title: 'Add Omni transition shell, navigation labels, utility bar, dashboard-first layout, ticket actions, chat modules, admin catalog, and analytics report library', priority: 'P0', status: 'done', epicId: 'E6' },
]

export const seedIssues: Issue[] = [
  {
    id: 'C-001',
    title: 'User clarified the expected result is a full omnichannel operations support solution',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-002',
    title: 'Rebuild plan accepted with generic support desk, full channel set, Command Center home, and delivery tracker',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-003',
    title: 'Progress automation updated to continue every 3 hours and email gbolahans@wakanow.com',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-004',
    title: 'Research, UI plan, architecture, and tracker docs rewritten for the Omni rebuild',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-005',
    title: 'Omni domain model, seed data, IndexedDB store, and app shell implemented',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-006',
    title: 'Omni Command, Unified Inbox, Live Channels, Customers, Knowledge, Automation, Analytics, Workforce, Admin, and Tracker screens implemented',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-007',
    title: 'Lint, production build, browser workflow verification, manifest check, and service worker asset check passed',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-008',
    title: 'Final progress email sent with tracker summary and delivery notes',
    status: 'closed',
    closedOn: '2026-05-25',
  },
  {
    id: 'C-009',
    title: 'Progress email delivery resumed with project tracker attached',
    status: 'closed',
    closedOn: '2026-05-26',
  },
  {
    id: 'C-010',
    title: 'Latest local state re-verified and progress email prepared with the tracker attachment',
    status: 'closed',
    closedOn: '2026-05-26',
  },
  {
    id: 'C-011',
    title: 'Current workspace state re-verified with lint and production build before sending the next progress update with the tracker attachment',
    status: 'closed',
    closedOn: '2026-05-26',
  },
  {
    id: 'C-012',
    title: 'SVP-ready UI improvement pass completed with clearer priority work, ticket operating signals, and next-best-action guidance',
    status: 'closed',
    closedOn: '2026-05-26',
  },
  {
    id: 'C-013',
    title: 'AI work queue automation locked as default-on behavior unless disabled in Setup',
    status: 'closed',
    closedOn: '2026-05-27',
  },
  {
    id: 'C-014',
    title: 'Independent Python backend vertical slice created with passing smoke tests and local API docs',
    status: 'closed',
    closedOn: '2026-05-27',
  },
  {
    id: 'C-015',
    title: 'Frontend now reads backend health, settings, tracker, analytics, and provider readiness and writes the AI automation toggle back to the independent API',
    status: 'closed',
    closedOn: '2026-05-27',
  },
  {
    id: 'C-060',
    title: 'Frontend operational alerts now appear in Command Center and Setup with supervisor/admin status actions',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-061',
    title: 'Operational alerts now have durable webhook delivery attempts with Setup delivery status visibility',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-062',
    title: 'Email outbound now has a configurable SMTP adapter and Setup provider-readiness visibility',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-063',
    title: 'Worker analytics now persist durable hourly rollups with an Insights backend history panel',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-064',
    title: 'Ticket CSAT feedback now persists in the database and feeds analytics summary, rollups, and Insights',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-065',
    title: 'Email inbound now has configurable IMAP polling through the backend worker and Setup readiness panel',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-066',
    title: 'SMS outbound now has a configurable HTTP provider adapter for queued public replies and Setup readiness',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-067',
    title: 'SMS signed webhooks now support inbound text tickets and outbound delivery receipts',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-068',
    title: 'WhatsApp Cloud API delivery and signed inbound/status callbacks now use the durable connector pipeline',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-069',
    title: 'Facebook Messenger Graph API delivery and signed inbound/delivery callbacks now use the durable connector pipeline',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-070',
    title: 'Instagram DM Graph API delivery and signed inbound/read callbacks now use the durable connector pipeline',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-071',
    title: 'Voice HTTP callback delivery and signed inbound/status callbacks now use the durable connector pipeline',
    status: 'closed',
    closedOn: '2026-06-03',
  },
  {
    id: 'C-072',
    title: 'Local TOTP MFA enrollment, confirmation, login enforcement, disable, and account-recovery reset are now backed by the database and visible in Setup',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-073',
    title: 'User access now supports permission profiles, allow/deny overrides, permission-aware route enforcement, and self-lockout protection',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-074',
    title: 'Audit governance now supports CSV/JSON export, configurable retention, admin pruning, worker pruning, and Setup controls',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-075',
    title: 'Attachment governance now supports lifecycle status, delete/purge, retention pruning, worker cleanup, and Setup controls',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-076',
    title: 'Attachment provider hardening now supports S3-compatible storage, external malware scanning, pre-storage blocking, and Setup readiness',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-077',
    title: 'Production identity now has an OIDC SSO boundary with PKCE authorization start, one-time callback state, existing-user linking, guarded provisioning, and Login/Setup readiness',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-078',
    title: 'Customer and ticket list APIs now support market-scoped search, filters, sorting, pagination headers, and count metadata',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-079',
    title: 'Company, customer, and ticket APIs now emit ETags and reject stale If-Match updates',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-080',
    title: 'Ticket contexts now include backend-ranked knowledge suggestions with scores, terms, and reasons',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-081',
    title: 'Response macros are database-backed, ticket-ranked, usage-counted, audit-visible, and composer-ready',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-082',
    title: 'Ticket fields are configurable by market/channel, validated on writes, and rendered across Setup and ticket forms',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-083',
    title: 'Setup is split into focused sections so user creation and ticket fields are easier to operate',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-084',
    title: 'Public portal answer search and ticket submission now use backend-ranked answers, portal fields, customer reuse, and audit history',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-085',
    title: 'Public portal ticket status lookup and customer replies now expose only public timeline entries and reopen tickets when customers respond',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-086',
    title: 'Support groups are now database-backed per market, shown in Setup with counters, and used by handoff routing choices',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-087',
    title: 'SLA policies are backend-managed by market and visible in Setup Automation',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-088',
    title: 'Production AI guidance uses Anthropic when configured and safe deterministic routing otherwise',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-089',
    title: 'Email and production credentials can be saved as write-only backend settings',
    status: 'closed',
    closedOn: '2026-06-04',
  },
  {
    id: 'C-090',
    title: 'Setup Connectors was decluttered into focused credential sections',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-091',
    title: 'Supervisor recommendations now rank blocked handoffs, queue pressure, and reassignment actions',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-092',
    title: 'Attachment signed links now carry token IDs and creator identity for correlated audits',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-093',
    title: 'Support-group team inboxes, handoff-forward email queueing, and backend global search are wired',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-094',
    title: 'Handoffs now create linked internal team tickets with full case context and a handoff-board Team ticket action',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-095',
    title: 'Setup now exposes a sanitized production account-request pack and email draft for gbolahans@wakanow.com',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-096',
    title: 'Admins can queue the production account-request email through a searchable internal readiness ticket',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-097',
    title: 'Setup tracks non-secret provider account references and generates an API_DOCS snippet',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-098',
    title: 'Setup exposes a production launch readiness checklist backed by live API evidence and sanitized next actions',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-099',
    title: 'Handoff-forward email replies now append to linked internal tickets instead of creating duplicate cases',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-100',
    title: 'Customer email replies now append to the original ticket, reopen non-open cases, and avoid duplicate ticket creation',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-101',
    title: 'Handoff-forward emails now include audited signed download links for clean active attachments',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-102',
    title: 'IMAP email intake now stores clean attachments and records blocked files without duplicating replayed messages',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-103',
    title: 'Public portal users can upload proof files to tickets and replies with sanitized attachment status',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'C-104',
    title: 'Agents can review backend-ranked duplicate ticket suggestions and merge sources with audited target/source history',
    status: 'closed',
    closedOn: '2026-06-05',
  },
  {
    id: 'P-001',
    title: 'Provision provider credentials for built email, social, SMS, voice, and alert adapters',
    status: 'pending',
  },
  {
    id: 'P-002',
    title: 'Add external dashboards/APM plus managed storage and scanning',
    status: 'pending',
  },
  {
    id: 'P-003',
    title: 'Connect historical support-desk import or sync when approved',
    status: 'pending',
  },
  {
    id: 'P-004',
    title: 'Provision production SSO/OIDC client credentials and harden tenant isolation',
    status: 'pending',
  },
  {
    id: 'P-005',
    title: 'Commit the workspace to git and open the first delivery PR when the review path is agreed',
    status: 'pending',
  },
]

export const seedResponseMacros: ResponseMacro[] = [
  {
    id: 'macro-payment-recovery',
    name: 'Duplicate payment recovery reply',
    body: 'Thanks for flagging this. I am checking the transaction reference, payment gateway state, and reversal timeline now. I will keep this ticket open until we confirm the duplicate charge is reversed or explain the next bank-side step.',
    language: 'en',
    channels: ['email', 'whatsapp', 'portal'],
    tags: ['billing', 'payment-risk', 'recovery'],
    shortcut: '/payment-reversal',
    active: true,
    usageCount: 0,
    updatedAt: now,
  },
  {
    id: 'macro-social-complaint',
    name: 'Public social complaint acknowledgement',
    body: 'Thanks for raising this with us. I am moving the private details into DM so we can protect your information, confirm ownership, and share the next update time without exposing account details publicly.',
    language: 'en',
    channels: ['facebook', 'instagram'],
    tags: ['social', 'complaint', 'recovery'],
    shortcut: '/social-ack',
    active: true,
    usageCount: 0,
    updatedAt: now,
  },
  {
    id: 'macro-sla-escalation',
    name: 'SLA escalation ownership update',
    body: 'I can see this is time-sensitive. I am escalating it now and will share the owner, current status, and next confirmed update time in this thread.',
    language: 'en',
    channels: [],
    tags: ['escalation', 'sla', 'priority'],
    shortcut: '/next-update',
    active: true,
    usageCount: 0,
    updatedAt: now,
  },
]

export const initialOmniState: OmniState = {
  version: 20,
  selectedScreen: 'command',
  selectedConversationId: 'conv-1004',
  selectedCustomerId: 'cust-4',
  selectedChannelId: 'all',
  filters: {
    channel: 'all',
    status: 'all',
    priority: 'all',
    sla: 'all',
    assignee: 'all',
    sentiment: 'all',
    search: '',
  },
  channels: seedChannels,
  conversations: seedConversations,
  customers: seedCustomers,
  agents: seedAgents,
  supportGroups: seedSupportGroups,
  articles: seedArticles,
  ticketFields: seedTicketFields,
  responseMacros: seedResponseMacros,
  rules: seedRules,
  slaPolicies: seedSlaPolicies,
  businessHours: [],
  ticketTemplates: [],
  tags: [],
  csatSurveys: [],
  emailNotifications: [],
  scenarioAutomations: [],
  customFieldDefinitions: [],
  handoffs: seedHandoffs,
  outbox: [],
  settings: {
    aiWorkQueueAutomationEnabled: true,
  },
  epics: seedEpics,
  backlog: seedBacklog,
  issues: seedIssues,
}
